# Evolution params
evolution_params:
  n_generations: 1000
  population_size: 200
  remove_population_pct: 0
  n_elites: 0
  mutation_rate: 0.2
  mutation_factor: 0.2
  save_path: results/bnh-constrained-longer

prescriptor_params:
  model_params:
    - type: linear
      in_features: 4
      out_features: 16
    - type: relu
    - type: linear
      in_features: 16
      out_features: 16
    - type: relu
    - type: linear
      in_features: 16
      out_features: 2
    - type: sigmoid
  device: mps

problem: bnh
eval_params:
  n_jobs: -1
  device: mps